### ISSUE TITLE
Can't find bundle for base name Resources, locale en_US

### ISSUE THREAD

**Issue by Yneth** [sargue/java-time-jsptags#5]
Hello,
I have some trouble getting the tag `javatime:parseLocalDate` running. When trying to open a page with javatime tag this error is thrown.

```
Caused by: javax.servlet.ServletException: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: java.lang.ExceptionInInitializerError
	at org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:905)
	at org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:838)
	at org.apache.jsp.WEB_002dINF.pages.user.requests_jsp._jspService(requests_jsp.java:155)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438)
	... 56 more
Caused by: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: java.lang.ExceptionInInitializerError
	at org.apache.jsp.tag.web.user_002dpage_tag$Helper.invoke(user_002dpage_tag.java:222)
	at org.apache.jsp.tag.web.site_002dpage_tag$Helper.invoke3(site_002dpage_tag.java:240)
	at org.apache.jsp.tag.web.site_002dpage_tag$Helper.invoke(site_002dpage_tag.java:269)
	at org.apache.jsp.tag.web.base_002dpage_tag.doTag(base_002dpage_tag.java:187)
	at org.apache.jsp.tag.web.site_002dpage_tag._jspx_meth_t_005fbase_002dpage_005f0(site_002dpage_tag.java:150)
	at org.apache.jsp.tag.web.site_002dpage_tag.doTag(site_002dpage_tag.java:112)
	at org.apache.jsp.tag.web.user_002dpage_tag._jspx_meth_t_005fsite_002dpage_005f0(user_002dpage_tag.java:139)
	at org.apache.jsp.tag.web.user_002dpage_tag.doTag(user_002dpage_tag.java:112)
	at org.apache.jsp.WEB_002dINF.pages.user.requests_jsp._jspx_meth_t_005fuser_002dpage_005f0(requests_jsp.java:172)
	at org.apache.jsp.WEB_002dINF.pages.user.requests_jsp._jspService(requests_jsp.java:142)
	... 59 more
Caused by: javax.servlet.jsp.JspException: javax.servlet.jsp.JspException: java.lang.ExceptionInInitializerError
	at org.apache.jsp.WEB_002dINF.pages.user.requests_jsp$Helper.invoke(requests_jsp.java:365)
	at org.apache.jsp.tag.web.user_002dpage_tag._jspx_meth_c_005fif_005f0(user_002dpage_tag.java:161)
	at org.apache.jsp.tag.web.user_002dpage_tag.access$0(user_002dpage_tag.java:144)
	at org.apache.jsp.tag.web.user_002dpage_tag$Helper.invoke0(user_002dpage_tag.java:194)
	at org.apache.jsp.tag.web.user_002dpage_tag$Helper.invoke(user_002dpage_tag.java:214)
	... 68 more
Caused by: javax.servlet.jsp.JspException: java.lang.ExceptionInInitializerError
	at org.apache.jsp.tag.web.partials.requests_002dpartial_tag.doTag(requests_002dpartial_tag.java:205)
	at org.apache.jsp.WEB_002dINF.pages.user.requests_jsp._jspx_meth_p_005frequests_002dpartial_005f0(requests_jsp.java:209)
	at org.apache.jsp.WEB_002dINF.pages.user.requests_jsp.access$1(requests_jsp.java:200)
	at org.apache.jsp.WEB_002dINF.pages.user.requests_jsp$Helper.invoke0(requests_jsp.java:323)
	at org.apache.jsp.WEB_002dINF.pages.user.requests_jsp$Helper.invoke(requests_jsp.java:357)
	... 72 more
Caused by: java.lang.ExceptionInInitializerError
	at net.sargue.time.jsptags.ParseSupport.doEndTag(ParseSupport.java:211)
	at org.apache.jsp.tag.web.partials.requests_002dpartial_tag._jspx_meth_javatime_005fparseLocalTime_005f0(requests_002dpartial_tag.java:614)
	at org.apache.jsp.tag.web.partials.requests_002dpartial_tag._jspx_meth_c_005fforEach_005f0(requests_002dpartial_tag.java:533)
	at org.apache.jsp.tag.web.partials.requests_002dpartial_tag.doTag(requests_002dpartial_tag.java:191)
	... 76 more
Caused by: java.util.MissingResourceException: Can't find bundle for base name Resources, locale en_US
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)
	at net.sargue.time.jsptags.Resources.<clinit>(Resources.java:52)
	... 80 more
```

**Comment by sargue** [comment]
Hi, thanks for reporting. This code is part of the original library from which this is forked.

On a fast review of the code seems that there is a _default_ bundle but it is not picked up. I will research more into this.

**Comment by sargue** [comment]
Could you please check your app with this snapshot version?

[java-time-jsptags-1.1.3-SNAPSHOT.jar.zip](https://github.com/sargue/java-time-jsptags/files/673789/java-time-jsptags-1.1.3-SNAPSHOT.jar.zip)
