### ISSUE TITLE
java.time.format.DateTimeParseException could not be parsed, unparsed text found at index 10

### ISSUE THREAD

**Issue by PashaTurok** [sargue/java-time-jsptags#9]
I use java-time-jsptags 1.1.4. In JPS I have `<javatime:parseLocalDateTime value="${date}" pattern="yyyy-MM-dd"/>` where date is of LocalDateTime. This is what I get:

```
Caused by: java.time.format.DateTimeParseException: Text '2018-05-01T10:30:55' could not be parsed, unparsed text found at index 10
 	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1952) ~[na:1.8.0_144]
 	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851) ~[na:1.8.0_144]
 	at net.sargue.time.jsptags.ParseSupport.doEndTag(ParseSupport.java:209) ~[java-time-jsptags-1.1.4.jar:1.1.4]
 	at org.apache.jsp.dynamic.jsp.unlocker_jsp._jspx_meth_javatime_parseLocalDateTime_0(unlocker_jsp.java:235) ~[na:na]
```

**Comment by sargue** [comment]
Are you sure you want to parse that or format and print it? Maybe you should be using `<javatime:format>` instead. See #8.

**Comment by PashaTurok** [comment]
Thank you for such quick answer. Yes, you are right. I had to use javatime:format.

**Comment by sargue** [comment]
You're welcome!
